export enum UrlInternal {
  VITE_BASE_URL = 'https://film-app-server.herokuapp.com',
  VITE_SEARCH_ADVANCED_URL = 'search/search-advanced',
  VITE_PREVIEW_VIDEOS_URL = 'preview/preview-videos',
  VITE_PREVIEW_VIDEO_MEDIA_URL = 'preview/preview-video-media',
  VITE_SEARCH_CONFIG_URL = 'search/search-config',
  VITE_HOME_PAGE_URL = 'home-page',
  VITE_SEARCH_LEADERBOARD_URL = 'search/search-leaderboard',
  VITE_MOVIE_DETAIL_URL = 'movie/movie-detail',
  VITE_MOVIE_MEDIA_URL = 'movie/movie-media',
  VITE_SEARCH_TOP_KEYWORDS_URL = 'search/search-top-keywords',
  VITE_SEARCH_WITH_KEYWORD_URL = 'search/search-with-keyword',
  VITE_TV_DETAIL_URL = 'tv/tv-detail',
  VITE_TV_EPISODE_MEDIA_URL = 'tv/tv-episode-media',
}
